### ISSUE TITLE
android.view.InflateException: Binary XML file line #12: Error inflating class EditText

### ISSUE THREAD

**Issue by GoodmanLi** [zaaach/CityPicker#29]
###显示Fragment的时候报这个错，Activity的Theme有设置。请问是什么原因啊？

```
Application crash
                                                                     android.view.InflateException: Binary XML file line #12: Error inflating class EditText
                                                                         at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:713)
                                                                         at android.view.LayoutInflater.rInflate(LayoutInflater.java:755)
                                                                         at android.view.LayoutInflater.parseInclude(LayoutInflater.java:839)
                                                                         at android.view.LayoutInflater.rInflate(LayoutInflater.java:745)
                                                                         at android.view.LayoutInflater.inflate(LayoutInflater.java:492)
                                                                         at android.view.LayoutInflater.inflate(LayoutInflater.java:397)
                                                                         at com.zaaach.citypicker.CityPickerDialogFragment.onCreateView(CityPickerDialogFragment.java:122)
                                                                         at android.support.v4.app.Fragment.performCreateView(Fragment.java:2261)
                                                                         at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1419)
                                                                         at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1750)
                                                                         at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1819)
                                                                         at android.support.v4.app.BackStackRecord.executeOps(BackStackRecord.java:797)
                                                                         at android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManager.java:2590)
                                                                         at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2377)
                                                                         at android.support.v4.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2332)
                                                                         at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2239)
                                                                         at android.support.v4.app.FragmentManagerImpl$1.run(FragmentManager.java:700)
                                                                         at android.os.Handler.handleCallback(Handler.java:733)
                                                                         at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                         at android.os.Looper.loop(Looper.java:136)
                                                                         at android.app.ActivityThread.main(ActivityThread.java:5333)
                                                                         at java.lang.reflect.Method.invokeNative(Native Method)
                                                                         at java.lang.reflect.Method.invoke(Method.java:515)
                                                                         at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:895)
                                                                         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:711)
                                                                         at dalvik.system.NativeStart.main(Native Method)
                                                                      Caused by: java.lang.UnsupportedOperationException: Can't convert to dimension: type=0x2
                                                                         at android.content.res.TypedArray.getDimensionPixelSize(TypedArray.java:478)
                                                                         at android.widget.TextView.<init>(TextView.java:991)
                                                                         at android.widget.EditText.<init>(EditText.java:60)
                                                                         at android.support.v7.widget.AppCompatEditText.<init>(AppCompatEditText.java:64)
                                                                         at android.support.v7.widget.AppCompatEditText.<init>(AppCompatEditText.java:60)
                                                                         at android.support.v7.app.AppCompatViewInflater.createView(AppCompatViewInflater.java:112)
                                                                         at android.support.v7.app.AppCompatDelegateImplV9.createView(AppCompatDelegateImplV9.java:1016)
                                                                         at android.support.v7.app.AppCompatDelegateImplV9.onCreateView(AppCompatDelegateImplV9.java:1073)
                                                                         at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:684)
                                                                         at android.view.LayoutInflater.rInflate(LayoutInflater.java:755) 
                                                                         at android.view.LayoutInflater.parseInclude(LayoutInflater.java:839) 
                                                                         at android.view.LayoutInflater.rInflate(LayoutInflater.java:745) 
                                                                         at android.view.LayoutInflater.inflate(LayoutInflater.java:492) 
                                                                         at android.view.LayoutInflater.inflate(LayoutInflater.java:397) 
                                                                         at com.zaaach.citypicker.CityPickerDialogFragment.onCreateView(CityPickerDialogFragment.java:122) 
                                                                         at android.support.v4.app.Fragment.performCreateView(Fragment.java:2261) 
                                                                         at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1419) 
                                                                         at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1750) 
                                                                         at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1819) 
                                                                         at android.support.v4.app.BackStackRecord.executeOps(BackStackRecord.java:797) 
                                                                         at android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManager.java:2590) 
                                                                         at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2377) 
                                                                         at android.support.v4.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2332) 
                                                                         at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2239) 
                                                                         at android.support.v4.app.FragmentManagerImpl$1.run(FragmentManager.java:700) 
                                                                         at android.os.Handler.handleCallback(Handler.java:733) 
                                                                         at android.os.Handler.dispatchMessage(Handler.java:95) 
                                                                         at android.os.Looper.loop(Looper.java:136) 
                                                                         at android.app.ActivityThread.main(ActivityThread.java:5333) 
                                                                         at java.lang.reflect.Method.invokeNative(Native Method) 
                                                                         at java.lang.reflect.Method.invoke(Method.java:515) 
                                                                         at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:895) 
                                                                         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:711) 
                                                                         at dalvik.system.NativeStart.main(Native Method) 
```

**Comment by GoodmanLi** [comment]
低级错误，眼花了,Theme没设置到位，Sorry.

**Comment by sshuai** [comment]
我也遇到了同样的问题，我看了一下我的styles里面的Theme是报错的，但是不影响程序运行，要打开这个页面就报这个错，哪位大神能指导一下，给个解决方法。
