### ISSUE TITLE
点击搜索框，一输入内容就崩掉，是你里面的代码报错，找不到rcy的那个方法

### ISSUE THREAD

**Issue by darkSuperman** [zaaach/CityPicker#33]
作者你好，在Fragment里面和Activity里面你都是这样。rcy根本没这个方法，怎么解决？

java.lang.NoSuchMethodError: No virtual method getItemDecorationAt(I)Landroid/support/v7/widget/RecyclerView$ItemDecoration; in class Landroid/support/v7/widget/RecyclerView; or its super classes (declaration of 'android.support.v7.widget.RecyclerView' appears in /data/app/com.bjbywx.wzt.wzt-2/split_lib_dependencies_apk.apk)
                                                                      at com.zaaach.citypicker.CityPickerDialogFragment.afterTextChanged(CityPickerDialogFragment.java:207)
                                                                      at android.widget.TextView.sendAfterTextChanged(TextView.java:8222)
                                                                      at android.widget.TextView$ChangeWatcher.afterTextChanged(TextView.java:10424)
                                                                      at android.text.SpannableStringBuilder.sendAfterTextChanged(SpannableStringBuilder.java:1218)
                                                                      at android.text.SpannableStringBuilder.replace(SpannableStringBuilder.java:579)
                                                                      at android.text.SpannableStringBuilder.replace(SpannableStringBuilder.java:509)
                                                                      at android.text.SpannableStringBuilder.replace(SpannableStringBuilder.java:508)
                                                                      at android.view.inputmethod.BaseInputConnection.replaceText(BaseInputConnection.java:844)
                                                                      at android.view.inputmethod.BaseInputConnection.commitText(BaseInputConnection.java:198)
                                                                      at com.android.internal.widget.EditableInputConnection.commitText(EditableInputConnection.java:183)
                                                                      at com.android.internal.view.IInputConnectionWrapper.executeMessage(IInputConnectionWrapper.java:353)
                                                                      at com.android.internal.view.IInputConnectionWrapper$MyHandler.handleMessage(IInputConnectionWrapper.java:93)
                                                                      at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                      at android.os.Looper.loop(Looper.java:177)
                                                                      at android.app.ActivityThread.main(ActivityThread.java:6634)
                                                                      at java.lang.reflect.Method.invoke(Native Method)
                                                                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:907)
                                                                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:797)

**Comment by darkSuperman** [comment]
哦，原来你的rcy是27的，才有getItemDecorationAt这个方法，我是25的，没有，改了之后就有了
