### ISSUE TITLE
调用报XML找不到

### ISSUE THREAD

**Issue by qq574699613** [zaaach/CityPicker#55]
android.view.InflateException: Binary XML file line #9: Binary XML file line #9: Error inflating class <unknown>
    Caused by: android.view.InflateException: Binary XML file line #9: Error inflating class <unknown>
    Caused by: java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Constructor.newInstance0(Native Method)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:334)
        at android.view.LayoutInflater.createView(LayoutInflater.java:651)
        at com.android.internal.policy.PhoneLayoutInflater.onCreateView(PhoneLayoutInflater.java:58)
        at android.view.LayoutInflater.onCreateView(LayoutInflater.java:724)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:792)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:734)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:867)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:828)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:519)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:427)
        at com.zaaach.citypicker.adapter.CityListAdapter.onCreateViewHolder(CityListAdapter.java:106)
        at com.zaaach.citypicker.adapter.CityListAdapter.onCreateViewHolder(CityListAdapter.java:30)
        at android.support.v7.widget.RecyclerView$Adapter.createViewHolder(RecyclerView.java:6685)
        at android.support.v7.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:5869)
        at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5752)
        at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5748)
        at android.support.v7.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2232)
        at android.support.v7.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1559)
        at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1519)
        at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:614)
        at android.support.v7.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:3812)
        at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:3529)
        at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:4082)
        at android.view.View.layout(View.java:19612)
        at android.view.ViewGroup.layout(ViewGroup.java:6055)
        at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1080)
        at android.view.View.layout(View.java:19612)
        at android.view.ViewGroup.layout(ViewGroup.java:6055)
        at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1791)
        at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1635)
        at android.widget.LinearLayout.onLayout(LinearLayout.java:1544)
        at android.view.View.layout(View.java:19612)
        at android.view.ViewGroup.layout(ViewGroup.java:6055)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
        at android.view.View.layout(View.java:19612)
        at android.view.ViewGroup.layout(ViewGroup.java:6055)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
        at android.view.View.layout(View.java:19612)
        at android.view.ViewGroup.layout(ViewGroup.java:6055)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
        at android.view.View.layout(View.java:19612)
        at android.view.ViewGroup.layout(ViewGroup.java:6055)
        at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1791)
        at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1635)
        at android.widget.LinearLayout.onLayout(LinearLayout.java:1544)
        at android.view.View.layout(View.java:19612)
        at android.view.ViewGroup.layout(ViewGroup.java:6055)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
07-03 14:46:09.906 16379-16379/com.xzx.social E/AndroidRuntime:     at com.android.internal.policy.DecorView.onLayout(DecorView.java:761)
        at android.view.View.layout(View.java:19612)
        at android.view.ViewGroup.layout(ViewGroup.java:6055)
        at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2512)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2228)
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1414)
        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6801)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1026)
        at android.view.Choreographer.doCallbacks(Choreographer.java:838)
        at android.view.Choreographer.doFrame(Choreographer.java:769)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1012)
        at android.os.Handler.handleCallback(Handler.java:789)
        at android.os.Handler.dispatchMessage(Handler.java:98)
        at android.os.Looper.loop(Looper.java:171)
        at android.app.ActivityThread.main(ActivityThread.java:6684)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:246)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:783)
     Caused by: java.lang.UnsupportedOperationException: Failed to resolve attribute at index 35: TypedValue{t=0x2/d=0x7f0100d5 a=-1}
        at android.content.res.TypedArray.getDrawableForDensity(TypedArray.java:946)
        at android.content.res.TypedArray.getDrawable(TypedArray.java:930)
        at android.view.View.<init>(View.java:5087)
        at android.view.ViewGroup.<init>(ViewGroup.java:597)
        at android.widget.FrameLayout.<init>(FrameLayout.java:92)
        at android.widget.FrameLayout.<init>(FrameLayout.java:87)
        at android.widget.FrameLayout.<init>(FrameLayout.java:82)
        	... 71 more

**Comment by qq574699613** [comment]
android:foreground="?attr/selectableItemBackground 下了源码下来发现是这句报错

**Comment by sshuai** [comment]
解决了没？

**Comment by sunshinecf** [comment]
Error:(32, 5) error: style attribute 'attr/cpCancelTextSize (aka com.house.supermarket:attr/cpCancelTextSize)' not found.

**Comment by sunshinecf** [comment]
这是为啥

**Comment by qq574699613** [comment]
太久了 @sunshinecf 有点记不清了...

**Comment by sshuai** [comment]
> 
> 
> 这是为啥

manifest里面调起的activity有没有写那个CustomDefaultCityPickerTheme这个style？

**Comment by qq574699613** [comment]
我后来换了一种方式,启动了一个新的Activity DefaultCityPickerTheme 然后设置了这个style 然后在这个Activity 里启动就可以了.不过我是直接把代码down下来,然后放进项目的,不是通过依赖,当时好像就是依赖的时候报的这个错误

**Comment by sshuai** [comment]
> 
> 
> 我后来换了一种方式,启动了一个新的Activity DefaultCityPickerTheme 然后设置了这个style 然后在这个Activity 里启动就可以了.不过我是直接把代码down下来,然后放进项目的,不是通过依赖,当时好像就是依赖的时候报的这个错误

依赖的你需要重写这个style ,  <style name="CustomDefaultCityPickerTheme" parent="AppTheme.NoActionBar">

        <item name="windowActionBar">false</item>
        <item name="windowNoTitle">true</item>

        <item name="cpCancelTextSize">@dimen/cp_cancel_text_size</item>
        <item name="cpCancelTextColor">@color/cp_color_gray</item>

        <item name="cpClearTextIcon">@mipmap/cp_icon_clear_all</item>
        <item name="cpSearchTextSize">@dimen/cp_search_text_size</item>
        <item name="cpSearchTextColor">@color/cp_color_gray_dark</item>
        <item name="cpSearchHintText">@string/cp_search_hint_text</item>
        <item name="cpSearchHintTextColor">@color/cp_color_gray_light</item>
        <item name="cpSearchCursorDrawable">@color/cp_color_gray_dark</item>

        <item name="cpListItemHeight">@dimen/cp_list_item_height</item>
        <item name="cpListItemTextSize">@dimen/cp_list_item_text_size</item>
        <item name="cpListItemTextColor">@color/cp_color_gray_deep</item>

        <item name="cpEmptyIcon">@mipmap/cp_icon_empty</item>
        <item name="cpEmptyIconWidth">@dimen/cp_empty_icon_width</item>
        <item name="cpEmptyIconHeight">@dimen/cp_empty_icon_height</item>
        <item name="cpEmptyText">@string/cp_no_result</item>
        <item name="cpEmptyTextSize">@dimen/cp_empty_text_size</item>
        <item name="cpEmptyTextColor">@color/cp_color_gray_deep</item>

        <item name="cpGridItemBackground">@drawable/cp_grid_item_bg</item>
        <item name="cpGridItemSpace">@dimen/cp_grid_item_space</item>

        <item name="cpSectionHeight">@dimen/cp_section_height</item>
        <item name="cpSectionTextSize">@dimen/cp_section_text_size</item>
        <item name="cpSectionTextColor">@color/cp_color_gray</item>
        <item name="cpSectionBackground">@color/cp_color_section_bg</item>

        <item name="cpIndexBarTextSize">@dimen/cp_index_bar_text_size</item>
        <item name="cpIndexBarNormalTextColor">@color/cp_color_gray</item>
        <item name="cpIndexBarSelectedTextColor">@color/cp_color_gray_dark</item>

        <item name="cpOverlayWidth">@dimen/cp_overlay_width</item>
        <item name="cpOverlayHeight">@dimen/cp_overlay_height</item>
        <item name="cpOverlayTextSize">@dimen/cp_overlay_text_size</item>
        <item name="cpOverlayTextColor">@android:color/white</item>
        <item name="cpOverlayBackground">@drawable/cp_overlay_bg</item>
    </style>
放在style下面 在清单里设置android:theme="@style/CustomDefaultCityPickerTheme"

**Comment by qq574699613** [comment]
嗯嗯那我下次就直接依赖用试试 .谢谢 @sshuai

**Comment by sshuai** [comment]
> 
> 
> 嗯嗯那我下次就直接依赖用试试 .谢谢 @sshuai

0.0我正在改代码，都不知道为啥你们回复的信息会抄送到我邮箱

**Comment by qq574699613** [comment]
很奇怪,因为我记得当时我是有写这个style的.下次如果要用再试试吧
