### ISSUE TITLE
mContentView = inflater.inflate(R.layout.cp_dialog_city_picker, container, false);

### ISSUE THREAD

**Issue by qiuwenxin** [zaaach/CityPicker#63]
mContentView = inflater.inflate(R.layout.cp_dialog_city_picker, container, false);这句话打开项目后点击选择城市闪退

**Comment by qiuwenxin** [comment]
用不了啊    一点按钮就闪退

**Comment by qiuwenxin** [comment]
build文件中是这样依赖的implementation 'com.zaaach:citypicker:2.0.2',
androidManifest文件中是这样写的
<activity
            android:name=".app_platform.new_platform.my.activity.MyInfoActivity"
            android:configChanges="orientation|keyboardHidden|screenSize"
            android:launchMode="singleTop"
            android:screenOrientation="portrait"
            android:theme="@style/DefaultCityPickerTheme"
            android:windowSoftInputMode="adjustPan"/>
点击事件是按使用说明中Step2写的
然后点击后报这个错误,我不太清楚是哪里出了问题  android.view.InflateException: Binary XML file line #9: Binary XML file line #9: Error inflating class <unknown>
                                                                          Caused by: android.view.InflateException: Binary XML file line #9: Error inflating class <unknown>
                                                                          Caused by: java.lang.reflect.InvocationTargetException
                                                                              at java.lang.reflect.Constructor.newInstance0(Native Method)
                                                                              at java.lang.reflect.Constructor.newInstance(Constructor.java:334)
                                                                              at android.view.LayoutInflater.createView(LayoutInflater.java:647)
                                                                              at com.android.internal.policy.PhoneLayoutInflater.onCreateView(PhoneLayoutInflater.java:58)
                                                                              at android.view.LayoutInflater.onCreateView(LayoutInflater.java:720)
                                                                              at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:788)
                                                                              at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:730)
                                                                              at android.view.LayoutInflater.rInflate(LayoutInflater.java:863)
                                                                              at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:824)
                                                                              at android.view.LayoutInflater.inflate(LayoutInflater.java:515)
                                                                              at android.view.LayoutInflater.inflate(LayoutInflater.java:423)
                                                                              at com.zaaach.citypicker.adapter.CityListAdapter.onCreateViewHolder(CityListAdapter.java:106)
                                                                              at com.zaaach.citypicker.adapter.CityListAdapter.onCreateViewHolder(CityListAdapter.java:30)
                                                                              at android.support.v7.widget.RecyclerView$Adapter.createViewHolder(RecyclerView.java:6519)
                                                                              at android.support.v7.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:5706)
                                                                              at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5589)
                                                                              at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5585)
                                                                              at android.support.v7.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2231)
                                                                              at android.support.v7.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1558)
                                                                              at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1518)
                                                                              at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:610)
                                                                              at android.support.v7.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:3719)
                                                                              at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:3436)
                                                                              at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:3988)
                                                                              at android.view.View.layout(View.java:19659)
                                                                              at android.view.ViewGroup.layout(ViewGroup.java:6075)
                                                                              at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1083)
                                                                              at android.view.View.layout(View.java:19659)
                                                                              at android.view.ViewGroup.layout(ViewGroup.java:6075)
                                                                              at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1791)
                                                                              at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1635)
                                                                              at android.widget.LinearLayout.onLayout(LinearLayout.java:1544)
                                                                              at android.view.View.layout(View.java:19659)
                                                                              at android.view.ViewGroup.layout(ViewGroup.java:6075)
                                                                              at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
                                                                              at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
                                                                              at android.view.View.layout(View.java:19659)
                                                                              at android.view.ViewGroup.layout(ViewGroup.java:6075)
                                                                              at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
                                                                              at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
                                                                              at android.view.View.layout(View.java:19659)
                                                                              at android.view.ViewGroup.layout(ViewGroup.java:6075)
                                                                              at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
                                                                              at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
                                                                              at android.view.View.layout(View.java:19659)
                                                                              at android.view.ViewGroup.layout(ViewGroup.java:6075)
                                                                              at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1791)
                                                                              at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1635)
                                                                              at android.widget.LinearLayout.onLayout(LinearLayout.java:1544)
                                                                              at android.view.View.layout(View.java:19659)
                                                                              at android.view.ViewGroup.layout(ViewGroup.java:6075)
                                                                              at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
11-07 01:29:24.754 4824-4824/com.shungyin.musicplatform E/AndroidRuntime:     at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
                                                                              at com.android.internal.policy.DecorView.onLayout(DecorView.java:761)
                                                                              at android.view.View.layout(View.java:19659)
                                                                              at android.view.ViewGroup.layout(ViewGroup.java:6075)
                                                                              at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2496)
                                                                              at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2212)
                                                                              at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1392)
                                                                              at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6752)
                                                                              at android.view.Choreographer$CallbackRecord.run(Choreographer.java:911)
                                                                              at android.view.Choreographer.doCallbacks(Choreographer.java:723)
                                                                              at android.view.Choreographer.doFrame(Choreographer.java:658)
                                                                              at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:897)
                                                                              at android.os.Handler.handleCallback(Handler.java:790)
                                                                              at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                              at android.os.Looper.loop(Looper.java:164)
                                                                              at android.app.ActivityThread.main(ActivityThread.java:6494)
                                                                              at java.lang.reflect.Method.invoke(Native Method)
                                                                              at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
                                                                              at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
                                                                           Caused by: java.lang.UnsupportedOperationException: Failed to resolve attribute at index 35: TypedValue{t=0x2/d=0x7f0100c6 a=-1}
                                                                              at android.content.res.TypedArray.getDrawableForDensity(TypedArray.java:944)
                                                                              at android.content.res.TypedArray.getDrawable(TypedArray.java:928)
                                                                              at android.view.View.<init>(View.java:5115)
                                                                              at android.view.ViewGroup.<init>(ViewGroup.java:597)
                                                                              at android.widget.FrameLayout.<init>(FrameLayout.java:92)
                                                                              at android.widget.FrameLayout.<init>(FrameLayout.java:87)
                                                                              at android.widget.FrameLayout.<init>(FrameLayout.java:82)
                                                                              	... 71 more

**Comment by qiuwenxin** [comment]
androidManifest文件中是这样写的
<activity
            android:name=".app_platform.new_platform.my.activity.MyInfoActivity"
            android:configChanges="orientation|keyboardHidden|screenSize"
            android:launchMode="singleTop"
            android:screenOrientation="portrait"
            android:theme="@style/DefaultCityPickerTheme"
            android:windowSoftInputMode="adjustPan"/>

**Comment by qiuwenxin** [comment]
androidManifest文件中是这样写的
            android:name=".app_platform.new_platform.my.activity.MyInfoActivity"
            android:configChanges="orientation|keyboardHidden|screenSize"
            android:launchMode="singleTop"
            android:screenOrientation="portrait"
            android:theme="@style/DefaultCityPickerTheme"
            android:windowSoftInputMode="adjustPan"

**Comment by qiuwenxin** [comment]
androidManifest文件中是这样写的
android:configChanges="orientation|keyboardHidden|screenSize"
android:launchMode="singleTop"
android:screenOrientation="portrait"
android:theme="@style/DefaultCityPickerTheme"
android:windowSoftInputMode="adjustPan"

**Comment by zaaach** [comment]
@qiuwenxin 试下最新版
