### ISSUE TITLE
报错了

### ISSUE THREAD

**Issue by wtjandjay** [zaaach/CityPicker#77]
Caused by: android.view.InflateException: Binary XML file line #12: Error inflating class EditText
    Caused by: java.lang.UnsupportedOperationException: Failed to resolve attribute at index 2: TypedValue{t=0x2/d=0x7f040105 a=-1}
        at android.content.res.TypedArray.getDimensionPixelSize(TypedArray.java:771)
        at android.widget.TextView.<init>(TextView.java:1303)
        at android.widget.EditText.<init>(EditText.java:88)
        at android.widget.EditText.<init>(EditText.java:84)
        at android.support.v7.widget.AppCompatEditText.<init>(AppCompatEditText.java:69)
        at android.support.v7.widget.AppCompatEditText.<init>(AppCompatEditText.java:65)
        at android.support.v7.app.AppCompatViewInflater.createEditText(AppCompatViewInflater.java:192)
        at android.support.v7.app.AppCompatViewInflater.createView(AppCompatViewInflater.java:114)
        at android.support.v7.app.AppCompatDelegateImpl.createView(AppCompatDelegateImpl.java:1266)
        at android.support.v7.app.AppCompatDelegateImpl.onCreateView(AppCompatDelegateImpl.java:1316)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:783)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:741)

**Comment by zaaach** [comment]
activity主题
