### ISSUE TITLE
有错误,运行崩溃

### ISSUE THREAD

**Issue by wangxian01** [zaaach/CityPicker#86]
android.view.InflateException: Binary XML file line #7: Binary XML file line #12: Error inflating class EditText
    Caused by: android.view.InflateException: Binary XML file line #12: Error inflating class EditText
    Caused by: java.lang.UnsupportedOperationException: Failed to resolve attribute at index 2: TypedValue{t=0x2/d=0x7f02007f a=-1}

**Comment by wangxian01** [comment]
Process: com.example.myapplication, PID: 28874
    android.view.InflateException: Binary XML file line #7: Binary XML file line #12: Error inflating class EditText
    Caused by: android.view.InflateException: Binary XML file line #12: Error inflating class EditText
    Caused by: java.lang.UnsupportedOperationException: Failed to resolve attribute at index 2: TypedValue{t=0x2/d=0x7f02007f a=-1}
        at android.content.res.TypedArray.getDimensionPixelSize(TypedArray.java:778)
        at android.widget.TextView.readTextAppearance(TextView.java:3740)
        at android.widget.TextView.<init>(TextView.java:1105)
        at android.widget.EditText.<init>(EditText.java:88)
        at android.widget.EditText.<init>(EditText.java:84)
        at android.support.v7.widget.AppCompatEditText.<init>(AppCompatEditText.java:69)
        at android.support.v7.widget.AppCompatEditText.<init>(AppCompatEditText.java:65)
        at android.support.v7.app.AppCompatViewInflater.createEditText(AppCompatViewInflater.java:192)
        at android.support.v7.app.AppCompatViewInflater.createView(AppCompatViewInflater.java:114)
        at android.support.v7.app.AppCompatDelegateImpl.createView(AppCompatDelegateImpl.java:1266)
        at android.support.v7.app.AppCompatDelegateImpl.onCreateView(AppCompatDelegateImpl.java:1316)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:783)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:741)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:874)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:835)
        at android.view.LayoutInflater.parseInclude(LayoutInflater.java:1006)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:870)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:835)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:515)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:423)
        at com.zaaach.citypicker.CityPickerDialogFragment.onCreateView(CityPickerDialogFragment.java:114)
        at android.support.v4.app.Fragment.performCreateView(Fragment.java:2439)
        at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1460)
        at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1784)
        at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1852)
        at android.support.v4.app.BackStackRecord.executeOps(BackStackRecord.java:802)
        at android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManager.java:2625)
        at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2411)
        at android.support.v4.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2366)
        at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2273)
        at android.support.v4.app.FragmentManagerImpl$1.run(FragmentManager.java:733)
        at android.os.Handler.handleCallback(Handler.java:891)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:207)
        at android.app.ActivityThread.main(ActivityThread.java:7470)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:958)

**Comment by Wilshion** [comment]
> Process: com.example.myapplication, PID: 28874
> android.view.InflateException: Binary XML file line #7: Binary XML file line #12: Error inflating class EditText
> Caused by: android.view.InflateException: Binary XML file line #12: Error inflating class EditText
> Caused by: java.lang.UnsupportedOperationException: Failed to resolve attribute at index 2: TypedValue{t=0x2/d=0x7f02007f a=-1}
> at android.content.res.TypedArray.getDimensionPixelSize(TypedArray.java:778)
> at android.widget.TextView.readTextAppearance(TextView.java:3740)
> at android.widget.TextView.(TextView.java:1105)
> at android.widget.EditText.(EditText.java:88)
> at android.widget.EditText.(EditText.java:84)
> at android.support.v7.widget.AppCompatEditText.(AppCompatEditText.java:69)
> at android.support.v7.widget.AppCompatEditText.(AppCompatEditText.java:65)
> at android.support.v7.app.AppCompatViewInflater.createEditText(AppCompatViewInflater.java:192)
> at android.support.v7.app.AppCompatViewInflater.createView(AppCompatViewInflater.java:114)
> at android.support.v7.app.AppCompatDelegateImpl.createView(AppCompatDelegateImpl.java:1266)
> at android.support.v7.app.AppCompatDelegateImpl.onCreateView(AppCompatDelegateImpl.java:1316)
> at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:783)
> at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:741)
> at android.view.LayoutInflater.rInflate(LayoutInflater.java:874)
> at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:835)
> at android.view.LayoutInflater.parseInclude(LayoutInflater.java:1006)
> at android.view.LayoutInflater.rInflate(LayoutInflater.java:870)
> at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:835)
> at android.view.LayoutInflater.inflate(LayoutInflater.java:515)
> at android.view.LayoutInflater.inflate(LayoutInflater.java:423)
> at com.zaaach.citypicker.CityPickerDialogFragment.onCreateView(CityPickerDialogFragment.java:114)
> at android.support.v4.app.Fragment.performCreateView(Fragment.java:2439)
> at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1460)
> at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1784)
> at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1852)
> at android.support.v4.app.BackStackRecord.executeOps(BackStackRecord.java:802)
> at android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManager.java:2625)
> at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2411)
> at android.support.v4.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2366)
> at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2273)
> at android.support.v4.app.FragmentManagerImpl$1.run(FragmentManager.java:733)
> at android.os.Handler.handleCallback(Handler.java:891)
> at android.os.Handler.dispatchMessage(Handler.java:102)
> at android.os.Looper.loop(Looper.java:207)
> at android.app.ActivityThread.main(ActivityThread.java:7470)
> at java.lang.reflect.Method.invoke(Native Method)
> at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
> at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:958)

同样遇到，不知道解决了没

**Comment by zaaach** [comment]
@wangxian01 @Wilshion 所在的activity设置主题了吗？
